env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
    - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - '@typescript-eslint'
    - 'prettier'
rules:
    'prettier/prettier':
        - error
    '@typescript-eslint/no-var-requires':
        - off
    no-undef:
        - off
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
