/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function isFree(port: number): boolean
export function isFreeTcp(port: number): boolean
export function isFreeUdp(port: number): boolean
export function randomFreePort(): number | null
export function randomFreeTcpPort(): number | null
export function randomFreeUdpPort(): number | null
export function selectFromGivenPort(port: number): number | null
export interface Selector {
    checkTcp?: boolean
    checkUdp?: boolean
    portFrom?: number
    portTo?: number
    maxRandomTimes?: number
}
export function selectFreePort(selector?: Selector | undefined | null): number | null
